version: '3'

services: 
    db:
        image: postgres
        env_file: .env

    web:
        build: .
        env_file: .env
        volumes: 
            - .:/app
        ports: 
            - "8000:${PORT}"
        depends_on: 
            - db